apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-pod-chaos-monkey
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kubernetes-pod-chaos-monkey
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-pod-chaos-monkey
    spec:
      containers:
      - name: kubernetes-pod-chaos-monkey
        image: codeurjc/kubernetes-pod-chaos-monkey
        imagePullPolicy: Always
        env:
        - name: TAG
          value: name
        - name: VALUE
          value: node-micro
        - name: NAMESPACE
          value: default
        - name: DELAY
          value: '30'
          

